name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  old-code:
    description: 'Folder with code for older commit'
    required: true
    default: 'old-code'
  new-code:
    description: 'Folder with code for current commit'
    required: true
    default: 'new-code'
  all-changed-files:
    description: 'All changed and modified files in'
    required: true
    default: '{}'
  ignore-list:
    description: 'Array of absolute path of files to ignore'
    required: false
    default: '[]'
  start-marker:
    description: 'Start marker in code'
    required: false
    default: 'srr-start'
  end-marker:
    description: 'End marker in code'
    required: false
    default: 'srr-end'
outputs:
  is-safe-change:
    description: 'Are the changes made safe'
runs:
  using: 'node16'
  main: 'dist/index.js'