name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  old-code:
    description: 'Folder with code for older commit'
    required: true
    default: 'old-code'
  new-code:
    description: 'Folder with code for current commit'
    required: true
    default: 'new-code'
  all-changed-files:
    description: 'All changed and modified files in'
    required: true
    default: '{}'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'